---
- name: Build the webserver Docker image
  community.docker.docker_image:
    name: "{{ webserver_image_name }}"
    build:
      path: "{{ webserver_dockerfile_path }}"
    source: build

- name: Copy NGINX config
  ansible.builtin.copy:
    src: nginx.conf
    dest: "{{ docker_dir }}/webserver/nginx.conf"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Deploy webserver container
  community.docker.docker_container:
    name: webserver
    image: "{{ webserver_image_name }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: wg_network
        ipv4_address: 10.8.2.10
    volumes:
      - "{{ docker_dir }}/webserver/nginx.conf:/etc/nginx/nginx.conf"
