---
# Setup via https://github.com/unkn0w/noobs/blob/main/scripts/chce_wireguard.sh, adapted for Ansible

- name: Prepare for wireguard-go building
  ansible.builtin.include_tasks: prerequsites.yml

- name: Install golang
  ansible.builtin.include_tasks: install_go.yml

- name: Build and install wireguard-go and wireguard-tools
  ansible.builtin.include_tasks: install_wg.yml

- name: Generate server keys
  ansible.builtin.stat:
    path: /etc/wireguard/server_private_key
  register: server_private_key_stat
  changed_when: server_private_key_stat.stat.exists == false

- name: Generate server keys
  ansible.builtin.shell: "wg genkey | tee /etc/wireguard/server_private_key | wg pubkey > /etc/wireguard/server_public_key"
  when: server_private_key_stat.stat.exists == false

- name: Setup server and client configs
  ansible.builtin.include_tasks: generate_configs.yml

- name: Stop Wireguard service
  ansible.builtin.service:
    name: wg-quick@wg0
    state: stopped

- name: Add environment variable to service
  ansible.builtin.shell: |
    sed -i '/RETRIES=infinity/{n;s/.*/Environment=WG_I_PREFER_BUGGY_USERSPACE_TO_POLISHED_KMOD=1/}' /lib/systemd/system/wg-quick@.service

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Add environment variables
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: "WG_I_PREFER_BUGGY_USERSPACE_TO_POLISHED_KMOD=1"
    state: present
    create: yes
  with_items:
    - ~/.profile
    - ~/.bashrc

- name: Start Wireguard service
  ansible.builtin.service:
    name: wg-quick@wg0
    state: started

- name: Clean-up
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/wireguard-tools
    - /tmp/wireguard-go
