---
- name: Switch between encrypted and unencrypted DNS depending on the user choice
  ansible.builtin.set_fact:
    wg_dns: >-
      {%- if enable_adguard_unbound_doh -%}
        {%- set wg_dns = "10.8.2.2" -%}
      {%- else -%}
        {%- if "cloudflare" in dns_nameservers -%}
          {%- set wg_dns = "1.1.1.1,1.0.0.1" -%}
        {%- elif "quad9" in dns_nameservers -%}
          {%- set wg_dns = "9.9.9.9,149.112.112.112" -%}
        {%- else -%}
          {%- set wg_dns = "8.8.8.8,8.8.4.4" -%}
        {%- endif -%}
      {%- endif -%}
      {{- wg_dns -}}

- name: Load the iptable_nat module (CentOS)
  when: 'ansible_os_family == "RedHat"'
  community.general.modprobe:
    name: iptable_nat
    persistent: present


- name: Backup resolver file
  ansible.builtin.copy:
    src: "/etc/resolv.conf"
    dest: "/etc/resolv.back"
    owner: root
    group: root
    mode: 0644

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  ansible.builtin.apt:
    packages: "{{ packages }}"
    state: present
  with_items:
    - "libmnl-dev"
    - "make"
    - "wireguard-tools"
    - "resolvconf"
    - git

- name: Stop and disable resolvconf
  ansible.builtin.service:
    name: resolvconf
    state: stopped
    enabled: no

- name: Restore the original resolver file
  ansible.builtin.copy:
    src: "/etc/resolv.back"
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    mode: 0644

- name: Ensure TUN/TAP is present
  ansible.builtin.file:
    path: /dev/net/tun
    state: present
    mode: 0666
    owner: root
    group: root

- name: Get wireguard-go source
  ansible.builtin.get_url:
    url: "https://git.zx2c4.com/wireguard-go/snapshot/wireguard-go-{{ wireguard_go_version }}.tar.xz"
    dest: "/tmp/wireguard-go-{{ wireguard_go_version }}.tar.xz"
    owner: root
    group: root
    mode: 0644

- name: Extract wireguard-go source
  ansible.builtin.unarchive:
    src: "/tmp/wireguard-go-{{ wireguard_go_version }}.tar.xz"
    dest: "/tmp/wireguard-go"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: Get wireguard-tools
  ansible.builtin.git:
    repo: "https://git.zx2c4.com/wireguard-tools"
    dest: "/tmp/wireguard-tools"

- name: Get golang
  ansible.builtin.get_url:
    url: "https://dl.google.com/go/go{{ golang_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ golang_version }}.linux-amd64.tar.gz"
    owner: root
    group: root
    mode: 0644

- name: Extract golang
  ansible.builtin.unarchive:
    src: "/tmp/go{{ golang_version }}.linux-amd64.tar.gz"
    dest: "/usr/local"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: Add GOROOT to PATH
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: "export GOROOT=/usr/local/go"
    state: present
    create: yes

- name: Add golang to PATH
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: "export PATH=$PATH:$GOPATH/bin:$GOROOT/bin"
    state: present
    create: yes

- name: Source /etc/profile
  ansible.builtin.shell: |
    source /etc/profile

- name: Add symlink for golang
  ansible.builtin.file:
    src: "/usr/local/go/bin/go"
    dest: "/usr/bin/go"
    state: link

- name: Build wireguard-go
  ansible.builtin.shell: |
    cd /tmp/wireguard-tools/src
    make
    make install

- name: Remove queueconstants.go
  ansible.builtin.file:
    path: "/tmp/wireguard-go/device/queueconstants_default.go"
    state: absent

- name: Get patched queueconstants.go
  ansible.builtin.get_url:
    url: "https://fx.vc-mp.eu/shared/queueconstants_default.go"
    dest: "/tmp/wireguard-go/device/queueconstants_default.go"
    owner: root
    group: root
    mode: 0644

- name: Build wireguard-go
  ansible.builtin.shell: |
    cd /tmp/wireguard-go
    make

- name: Copy wireguard-go to /usr/bin
  ansible.builtin.copy:
    src: "/tmp/wireguard-go/wireguard-go"
    dest: "/usr/bin/wireguard-go"
    owner: root
    group: root
    mode: 0755

- name: Generate server keys
  ansible.builtin.shell: |
    wg genkey | tee /etc/wireguard/server_private_key | wg pubkey > /etc/wireguard/server_public_key

- name: Chmod keys
  ansible.builtin.shell: |
    chmod 600 /etc/wireguard/*private_key*

- name: Load server private key
  ansible.builtin.slurp:
    src: /etc/wireguard/server_private_key
  register: server_private_key

- name: Load server public key
  ansible.builtin.slurp:
    src: /etc/wireguard/server_public_key
  register: server_public_key

- name: Generate client keys
  ansible.builtin.shell: |
    wg genkey | tee /etc/wireguard/client_private_key{{ item }} | wg pubkey > /etc/wireguard/client_public_key{{ item }}
  loop: "{{ range(1, wg_clients + 1) | list }}"

- name: Load client private keys
  ansible.builtin.set_fact:
    client_private_keys: "{{ client_private_keys | default([]) + [item.content] }}"
  loop: "{{ range(1, wg_clients + 1) | list }}"

- name: Load client public keys
  ansible.builtin.set_fact:
    client_public_keys: "{{ client_public_keys | default([]) + [item.content] }}"
  loop: "{{ range(1, wg_clients + 1) | list }}"

- name: Generate client configurations
  ansible.builtin.template:
    src: client.conf.j2
    dest: /etc/wireguard/client{{ item }}.conf
  loop: "{{ range(1, wg_clients + 1) | list }}"

- name: Create wg0.conf
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0644

- name: Stop Wireguard service
  ansible.builtin.service:
    name: wg-quick@wg0
    state: stopped

- name: Add environment variable to service
  ansible.builtin.shell: |
    sed -i '/RETRIES=infinity/{n;s/.*/Environment=WG_I_PREFER_BUGGY_USERSPACE_TO_POLISHED_KMOD=1/}' /lib/systemd/system/wg-quick@.service

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Add environment variables
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: "WG_I_PREFER_BUGGY_USERSPACE_TO_POLISHED_KMOD=1"
    state: present
    create: yes
  with_items:
    - ~/.profile
    - ~/.bashrc

- name: Start Wireguard service
  ansible.builtin.service:
    name: wg-quick@wg0
    state: started

- name: Clean-up
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/wireguard-tools
    - /tmp/wireguard-go
